config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 

  root 'home#top'
  resources :users, only: [:show]

  get    'game/:id'  => 'folders#game'

  resources :folders do
    resources :posts
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_secure_password

  has_many :folders, dependent: :destroy

  validates :name, presence: true
  # validates :email, presence: true
  # validates :password, presence: true
  mount_uploader :avatar, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :logged_in_user, only: [:edit, :destroy]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        redirect_to folders_path
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        render 'new'
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      redirect_to user_path(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end


  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to folders_path
  end

  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    redirect_to new_user_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in?, only: [:edit, :destroy]
  # before_action :correct_user,   only: [:edit, :update,:destroy]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @folders = @user.folders.all.page(params[:page]).per(10)
  end


  def edit  
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to @user
      flash[:success] = "「#{@user.name}」でユーザー登録しました"
    else
      render "edit"
    end
  end

  private

    # def user_params
    #   params.require(:user).permit(:name, :email, :avatar, :password,:password_confirmation)
    # end

    # def user_edit_params
    #   params.require(:user).permit(:name, :email)
    # end    
    # def correct_user
    #   @user = User.find(params[:id])
    #   redirect_to folders_path unless current_user?(@user)
    #   flash[:danger] = "ユーザーの編集は、本人しかできません。"
    # end

end

app/views/users/edit.html.erb
<div class="jumbotron">
  <h1 class="display-4">ユーザー編集</h1>
    <%= form_with model:@user,local:true,class: "form-inline" do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.text_field :name,placeholder: "名前を入力",class: "form-control w-75" %>
      <%= f.text_field :email,placeholder: "emailを入力",class: "form-control w-75" %>
      <%= f.text_field :password,placeholder: "passwordを入力",class: "form-control w-75" %>
      <%= f.text_field :password_confirmation,placeholder: "password(確認)を入力",class: "form-control w-75" %>
      <%= f.submit "登録",class: "btn btn-primary submit-btn" %>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="jumbotron">
  <h1 class="display-4">ユーザー新規登録</h1>
    <%= form_with model:@user,local:true,class: "form-inline" do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.text_field :name,placeholder: "名前を入力",class: "form-control w-75" %>
      <%= f.text_field :email,placeholder: "emailを入力",class: "form-control w-75" %>
      <%= f.text_field :password,placeholder: "passwordを入力",class: "form-control w-75" %>
      <%= f.text_field :password_confirmation,placeholder: "password(確認)を入力",class: "form-control w-75" %>
      <%= f.submit "登録",class: "btn btn-primary submit-btn" %>
    <% end %>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <%= link_to "", edit_user_registration_path(@user),class:"fas fa-user-edit fa-border fa-2x mb-3 user-edit" %>
<% end %>
<div class="text-center">
  <div class="user-name-show">
    <% if @user.avatar? %>
      <%= image_tag @user.avatar.to_s, class:"icon" %>
    <% else %>
      <image src="/assets/default_user_image.jpg" class="icon" %>
    <% end %>
    <%= @user.name %> 
  </div>
  <p class="lead mt-3">Myフォルダ一覧</p>
</div>

<% if @folders.blank? %>
    <div class="card mx-auto" style="width: 90%;">
      <div class="card-body text-center">
        フォルダが投稿されていません。
      </div>
    </div>
<% else %>
  <% @folders.each do |folder| %>
    <div class="card mx-auto" style="width: 90%;">
      <div class="card-body">
        <span class="user-name"><%= folder.user.name %></span>
        <p>
        <span class="card-title"><%= folder.title %></span>
        <span class="float-right">
          <%= link_to "","/game/#{folder.id}",class: "fas fa-gamepad fa-border fa-2x" %>
          <%= link_to "",folder_posts_path(folder),class: "fas fa-folder-open fa-border fa-2x" %>
          <%= link_to "",edit_folder_path(folder),class: "fas fa-edit fa-border fa-2x" %>
          <%= link_to "",new_folder_post_path(folder),class: "fas fa-plus fa-border fa-2x" %>
          <%= link_to "",folder_path(folder), method: :delete,class:"fas fa-trash-alt fa-border fa-2x", data: { confirm: "本当に削除してよろしいですか？\n(フォルダは復元できません。)" } %>
          <%#= link_to "",user_folder_path(folder),class: "fas fa-gamepad fa-border fa-2x" %>
          <%#= link_to "",new_user_folder_post_path(folder),class: "fas fa-folder-open fa-border fa-2x" %>      
        </span>
      </div>
    </div>
  <% end %>
<% end %>

<%= paginate @folders %>