config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 

  root 'home#top'
  resources :users, only: [:show]

  get    'game/:id'  => 'folders#game'

  resources :folders do
    resources :posts
  end 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :folder
  # belongs_to :user

  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :correct_user, only: [:new, :create, :destroy]

  def index
    @folder = Folder.find(params[:folder_id])
    @posts = @folder.posts.all
    # .order("RAND()").limit(1000) ランダムに表示できる
  end

  def new
    @folder = Folder.find(params[:folder_id])
    @post = @folder.posts.new
  end

  def create
    @folder = Folder.find(params[:folder_id])
    @post = @folder.posts.build(post_params)
    if @post.save
      redirect_back(fallback_location: new_folder_post_path)
      flash[:notice] = "「#{@post.content}」を投稿しました"
    else
      render "new"
    end
  end
  
  def destroy
    @folder = Folder.find(params[:folder_id])
    @post = @folder.posts.find(params[:id])
    @post.destroy
    redirect_back fallback_location: root_path, notice: "トークテーマを削除しました"
  end

  def edit  
    
  end

  private

    def post_params
      params.require(:post).permit(:content)
    end

end

app/views/posts/edit.html.erb
posts#edit

app/views/posts/index.html.erb
<% 
=begin
%>

あとで機能を追加する
フォルダ名:<%= @folder.title %>
<%= form_with model:[@folder, @folder.posts.build],local:true,class: "form-inline" do |f| %>
  <%= f.text_field:content,placeholder: "トピックを入力",class: "form-control w-75" %>
  <%= f.submit "投稿",class: "btn btn-primary submit-btn" %>
<% end %>

<%= link_to "ゲーム開始！",folder_path(@folder), class:"btn btn-info btn-lg game-btn" %>

<%
=end
%>

<div class="text-center">
  <div class="user-name-show">
    <% if @folder.user.avatar? %>
      <%= image_tag @folder.user.avatar.to_s, class:"icon" %>
    <% else %>
      <image src="/assets/default_user_image.jpg" class="icon" %>
    <% end %>
    <%= @folder.user.name %> 
  </div>
</div>

<div class="text-center">
  <div class="user-name-show"><%#= @user.name %> </div>
  <%#= link_to "", edit_user_registration_path(@user),class:"fas fa-user-edit fa-border fa-2x mb-3" %>
  <p class="lead mt-3">「<%= @folder.title %>」のトピック一覧</p>
</div>

<% if @posts.blank? %>
  <div class="card mx-auto" style="width: 90%;">
    <div class="card-body text-center">
      トピックが投稿されていません。
    </div>
  </div>
<% else %>
  <% @posts.each do |post| %>
    <div class="card mx-auto" style="width: 90%;">
      <div class="card-body">
        <span class="card-title"><%= post.content %></span>
        <div class="float-right">
          <%#= link_to "編集",edit_folder_post_path(post),class: "btn btn-primary" %> 
          <%= link_to "削除",folder_post_path(@folder,post), method: :delete,class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="jumbotron">
  <h2 class="folder-title" ></h2>
  <h1 class="display-4 ">「<%= @folder.title %>」にトピックを投稿</h1>
  <p  class="lead">ランダムに表示したいトピックを投稿する。</p>
    <%= form_with model:[@folder, @folder.posts.build],local:true,class: "form-inline" do |f| %>
      <%= f.text_field:content,placeholder: "トピックを入力",class: "form-control w-75", autofocus: true %>
      <%= f.submit "投稿",class: "btn btn-primary submit-btn" %>
    <% end %>
    <div class="text-center">
    <%= link_to "ゲーム開始","/game/#{@folder.id}", class:"btn btn-info btn-lg game-btn" %>
    </div>
</div>

app/views/posts/show.html.erb
posts#show