config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 

  root 'home#top'
  resources :users, only: [:show]

  get    'game/:id'  => 'folders#game'

  resources :folders do
    resources :posts
  end 
end

app/views/layouts/_footer.html.erb
<% 
=begin
%>

コメントアウトしてる場所



<header class="navbar navbar-expand-xl navbar-light bg-light">
      <%= link_to "",user_path(current_user),class:"fas fa-user fa-border fa-3x w-25" %>    
      <%= link_to "", folders_path,class: "fas fa-list fa-border fa-3x w-25" %>
      <%= link_to "", new_folder_path,class: "fas fa-folder-plus fa-border fa-3x w-25" %>
      <%= link_to "", destroy_user_session_path, method: :delete,class:"fas fa-sign-out-alt fa-border fa-3x w-25"  %>
</header>


<%
=end
%>

app/views/layouts/_header.html.erb
<script>
  $(function(){
      $('.dropdwn li').hover(function(){
          $("ul:not(:animated)", this).slideDown();
      }, function(){
          $("ul.dropdwn_menu",this).slideUp();
      });
  });
</script>

<header class="sticky-top">
  <% if user_signed_in? %>
    <div class="header-logo"><%= link_to "トピつく。", folders_path %></div>
  <% else %>
    <div class="header-logo"><%= link_to "トピつく。", root_path %></div>
  <% end %>
  <div class="float-right header-right mt-1">
     <ul class="dropdwn">
      <li ><span class="far fa-caret-square-down fa-border fa-3x"></span>
          <ul class="dropdwn_menu">
            <li><%= link_to "フォルダリスト", folders_path %></li>           
            <% if user_signed_in? %>
              <li><%= link_to "フォルダ作成", new_folder_path %></li> 
            <% end %>
          </ul>
      </li>    
    </ul>       
  </div>      
  <div class="float-left header-left mt-1">
    <ul class="dropdwn">
      <li><span class="fas fa-user fa-border fa-3x"></span>
        <ul class="dropdwn_menu">
          <% if user_signed_in? %>
            <li><%= link_to "プロフィール",user_path(current_user) %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>  
          <% else %>
            <li><%= link_to "アカウント作成", new_user_registration_path %></li> 
            <li><%= link_to "ログイン", new_user_session_path %></li> 
          <% end %>          
        </ul>
      </li>  
    </ul>          
  </div>    
</header>

     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomTalking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>

    <% unless current_page?(root_path) %>
      <%= render 'layouts/header'%>
    <% end %>    
    <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <%= notice %>
        </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <%= alert %>
    </div>
    <% end %>    
    <% unless current_page?(root_path) %>
      <div class="container">
        <%= yield %>
      </div>       
    <% else %>
      <%= yield %>
    <% end %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>